<a href="https://colab.research.google.com/github/Satyam-Mittal2527/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU.")

GPU is not available. Using CPU.


## Creating a Tensor

In [5]:
#using empty
a = torch.empty(2,3)

In [6]:
#Check type
type(a)

torch.Tensor

In [7]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.8555, 0.9055, 0.3483],
        [0.8533, 0.5564, 0.8233]])

In [10]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [16]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6066965718324227382, 3545241344689190448, 6498749453568521518]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

## Tensor Data Types

In [24]:
x.dtype

torch.int64

In [26]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
# assign data type
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [30]:
# using to()
float_x  =x.to(torch.float32)

## Mathematical Opertions

In [34]:
# 1. Scalar Operations
x = torch.rand(2,3)
x

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [41]:
#Addition
x + 2
#substraction
x -2
#Multiplication
x * 3
#Division
x / 2
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.1972, 0.8984, 0.5543],
        [0.2393, 0.0588, 0.4905]])

## Element wise operations

In [45]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])
tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])


In [51]:
#add
a + b
#substraction\
a -b
#multiple
a * b
#division
a / b
#power
a ** b
#mod
a % b

tensor([[0.2839, 0.0458, 0.4450],
        [0.3591, 0.4563, 0.3389]])

In [52]:
c = torch.tensor([1,-2,-3,-4])

In [53]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [54]:
torch.neg(c)

tensor([-1,  2,  3,  4])

In [55]:
d = torch.tensor([1.9,2.2,3.4, 5.6])

In [57]:
torch.ceil(d)

tensor([2., 3., 4., 6.])

In [58]:
torch.floor(d)

tensor([1., 2., 3., 5.])

In [60]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.2000, 3.0000, 3.0000])

## 3. Reuction Operation

In [80]:
e = torch.randint(size=(2,3), low = 0, high=10, dtype=torch.float32)
e

tensor([[8., 3., 3.],
        [5., 0., 6.]])

In [66]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)

tensor([10, 15])

In [69]:
#mean
torch.mean(e, dtype = torch.float32)
#mean along cols
torch.mean(e, dim= 0 ,dtype = torch.float32)

tensor([4.5000, 4.0000, 4.0000])

In [70]:
# median
torch.median(e)

tensor(4)

In [72]:
# max and min
torch.min(e)
torch.max(e)

tensor(8)

In [74]:
#product
torch.prod(e)

tensor(0)

In [81]:
#standard deciation
torch.std(e)

tensor(2.7869)

In [82]:
torch.var(e)

tensor(7.7667)

In [83]:
# argmax
torch.argmax(e)

tensor(0)

In [84]:
#argmin
torch.argmin(e)

tensor(4)

## Martix Operations

In [86]:
f = torch.randint(size=(2,3), low = 0, high=10)
g = torch.randint(size=(3,2), low = 0, high=10)

In [87]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 9, 29],
        [31, 39]])

In [88]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [90]:
#transpose
torch.transpose(f, 0, 1)

tensor([[5, 2],
        [0, 7],
        [4, 1]])

In [92]:
h = torch.randint(size=(3,3), low = 0, high=10, dtype=torch.float32)
h

tensor([[1., 4., 5.],
        [6., 9., 2.],
        [3., 1., 0.]])

In [93]:
#determinant
torch.det(h)

tensor(-83.)

In [94]:
#inverse
torch.inverse(h)

tensor([[ 0.0241, -0.0602,  0.4458],
        [-0.0723,  0.1807, -0.3373],
        [ 0.2530, -0.1325,  0.1807]])

## Comparision Operations

In [95]:
i = torch.randint(size=(2,3), low = 0, high=10)
j = torch.randint(size=(2,3), low = 0, high=10)

In [100]:
# greatar than
i > j
#less tham
i < j
# equal to
i == j
# not queal to
i != j

tensor([[True, True, True],
        [True, True, True]])

## Special Function

In [111]:
k = torch.randint(size=(2,3), low = 0, high=10, dtype=torch.float32)
k

tensor([[0., 5., 1.],
        [0., 0., 2.]])

In [112]:
# log
torch.log(k)

tensor([[  -inf, 1.6094, 0.0000],
        [  -inf,   -inf, 0.6931]])

In [113]:
# exp
torch.exp(k)

tensor([[  1.0000, 148.4132,   2.7183],
        [  1.0000,   1.0000,   7.3891]])

In [114]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.2361, 1.0000],
        [0.0000, 0.0000, 1.4142]])

In [115]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9933, 0.7311],
        [0.5000, 0.5000, 0.8808]])

In [116]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.5000, 0.9933, 0.2689],
        [0.5000, 0.0067, 0.7311]])

In [117]:
#relu
torch.relu(k)

tensor([[0., 5., 1.],
        [0., 0., 2.]])

## Inplace Operations

In [124]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.7667, 0.2269, 0.7555],
        [0.6458, 0.3673, 0.1770]])
tensor([[0.2966, 0.9925, 0.2103],
        [0.1292, 0.1719, 0.9127]])


In [125]:
m.add_(n)

tensor([[1.0633, 1.2194, 0.9659],
        [0.7750, 0.5392, 1.0897]])

## copying a tensor'

In [128]:
o = torch.rand(2,3)
o

tensor([[0.6818, 0.1953, 0.9991],
        [0.1133, 0.0135, 0.1450]])

In [135]:
#Copyig using clone()
p = o.clone()

In [136]:
p

tensor([[0.6818, 0.1953, 0.9991],
        [0.1133, 0.0135, 0.1450]])

## tensor Operations using GPU

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [5]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.0667, 0.0329, 0.2807],
        [0.9269, 0.4390, 0.1161]], device='cuda:0')

In [8]:
# moving tensors in GPU
a = torch.rand(2,3)
b = a.to(device)

In [1]:
import torch
import time

size = 10000

# Create matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# CPU computation
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")


# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# GPU computation
torch.cuda.synchronize()  # Ensure GPU is ready
start_time = time.time()

result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)

torch.cuda.synchronize()  # Wait for GPU computation to finish
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

print(f"\nSpeedup (CPU time / GPU time): {cpu_time/gpu_time:.2f}x")

Time on CPU: 16.8942 seconds
Time on GPU: 0.7100 seconds

Speedup (CPU time / GPU time): 23.80x


## reshaping Tensors

In [2]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [7]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
b = torch.rand(2,3,4)
b

tensor([[[0.0467, 0.0949, 0.7835, 0.8005],
         [0.9616, 0.5557, 0.9014, 0.4141],
         [0.0729, 0.9363, 0.9807, 0.9837]],

        [[0.9758, 0.6781, 0.1028, 0.8958],
         [0.7846, 0.9189, 0.6185, 0.7960],
         [0.2335, 0.8083, 0.8970, 0.2693]]])

In [9]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [10]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [11]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and PyTorch

In [12]:
import numpy as np

In [13]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [14]:
b = a.numpy()

In [16]:
type(b)

numpy.ndarray

In [18]:
c = np.array([1,2,3])

In [19]:
torch.from_numpy(c)

tensor([1, 2, 3])